version: '3'
services:
  api:
    build: ./api
    hostname: api
    ports:
     - "5002:5002"

  go:
    build: ./go
    ports:
     - "5001:5001"
    environment:
     - HOST=api
    links:
     - api

  netcore:
    build: ./netcore
    ports:
     - "5000:5000"
    environment:
     - HOST=api
    links:
     - api


